---
- hostname:
    name: "{{ inventory_hostname }}"
  become: true
  become_user: root
  become_method: sudo

- copy:
    dest: "/etc/resolv.conf"
    content: nameserver 114.114.114.114
  become: true
  become_user: root
  become_method: sudo