---
#- name: update /etc/hosts
#  copy:
#    src: hosts
#    dest: /etc/hosts
#    owner: root
#    group: root
 #   mode: 0644
  #  backup: yes
#  become: true
#  become_user: root
#  become_method: sudo
- name: update /etc/hosts
  template: src=etc-hosts.j2 dest=/etc/hosts